### ISSUE TITLE
data-nick="*" should be data-nick="nick" on ACTIONs

### ISSUE THREAD

**Issue by Zarthus** [korobi/Korobi#50]
``` html
<div data-nick="*" data-event-id="550dcb24e4b035e883f4c19b" data-event-type="action" class="line js-hl" data-line-num="122">
  <span class="timestamp">19:48:52</span>
  <span class="nick irc--07-df ">*</span>
  <span class="message"><span class="irc--07-df">Zarthus</span> has never actually played before</span>
</div>
```

note: this also is true for `<--` and `-->` and `--`

**Comment by bendem** [comment]
That could be fixed by moving `nick` to `displayName` (using `LogParser::getDisplayName`) and changing `LogParser::getActorName` to return the nickname everytime [here](https://github.com/korobi/Web/blob/751a90ce9b2c26cd196b8964757a5966ec97a590/src/Korobi/WebBundle/Controller/ChannelController.php#L262).
