### ISSUE TITLE
Listen to phrases in a blacklist and react to those by kicking, banning, warning, etc.

### ISSUE THREAD

**Issue by kashike** [korobi/Korobi#56]
ref korobi/Korobi#54
ref korobi/Korobi#55

**Comment by lol768** [comment]
Perhaps a weighting system would work. Non-ascii phrases flooded could be deemed more likely to be spam

**Comment by Zarthus** [comment]
I don't want the service to alter my logs. Especially for cases when people report people and I look back in the logs. If I see no spam, I most likely will ban the user for trying to get someone else banned.

In other words: I **strongly** disagree. Do not let Korobi alter any logs. If you MUST implement this, do it either by option that is default off, or by greying them out and collapsing them

Edit: it appears this issue is meant to ban the user, not filter the logs. Disregard my comment. (but you should really clarify that somewhere so others don't get confused)

**Comment by lol768** [comment]
For anyone who comes across the issue, AFAIK there are no plans to alter logs - the goal is to automatically punish (kick/ban/both) users who are spamming. See https://korobi.io/esper/drtshock/logs#L102,103,104,109,110 https://twitter.com/drtshock/status/582698147903774720 for more details.
