### ISSUE TITLE
Vote on future route choices!

### ISSUE THREAD

**Issue by lol768** [korobi/Korobi#72]
We need help deciding on how best to structure the routes for the site! Please vote below if you have a few seconds.

Prefix Options:
- [ ]  `/irc/`
- [x] `/network/`

Route Options:
- [ ] `/{prefix}/{network}/{channel}/{component}/`
- [x]  `/{prefix}/{network}/channel/{channel}/{component}/`
- [ ]  `/{prefix}/{network}/chan/{channel}/{component}/`
- [ ] `/{prefix}/{network}/view/{channel}/{component}/`

Thanks :smile:

**Comment by Zarthus** [comment]
The /network prefix for sure with /channel/{channel}/{component}, evilmidget on irc concluded my thoughts on it nicely.

```
(00:39:31) <+evilmidget38> I feel like /network/ makes more sense than irc for two reasons: 1) It's more consistent with the later /channel/{channel} and 2) It's more descriptive of the network name parameter.
```

`/network/{network}/channel/{channel}/{component}/` 
It's just gorgeous and I would like to make love to it.

**Comment by lol768** [comment]
What Zarthus said

**Comment by lol768** [comment]
What Zarthus said, minus the bit about making love to a route structure.

**Comment by kashike** [comment]
I agree with [@Zarthus](https://github.com/korobi/Korobi/issues/72#issuecomment-113664519).

**Comment by natemort** [comment]
What @lol768 said, plus the bit about making love to a route structure.

**Comment by bendem** [comment]
URIs represent the hierarchic structure of a website; the current navigation scheme of korobi to get from homepage to a channel component is `networks -> network -> channel -> component`. It would thus make sense to me to have some kind of representation like `/networks/{network}/{channel}/{component}/{component option}`.

Removing each part of the URI should imo send you back to the parent page which wouldn't work with `{network}/{channel}/channel/{component}/` (If you put channel information on `{network}/channel/{channel}/`, what'll `{network}/channel` contain?).

I also vote for the `networks` prefix for the reason mentioned above (when removing `{network name}` from `{prefix}/{network name}`, I expect to get back to the network list) and because when I create a directory strucure, I generally use the plural for the directories which'll contain a bunch of things of the same kind (`videos`, `pictures`, `projects`). It doesn't really make sense that when I'll navigate inside that tree, that name would change because I choose one specific item in it.

**Comment by bendem** [comment]
After speaking with Zarthus, I see I missed one of the problems. A network isn't only about channels, it also has stats. I'm thus voting for `{prefix}/{network}` containing the network landing page and `{prefix}/{network}/channel` containing the channels of the network.

My vote goes then to `networks` for the prefix and `{prefix}/{network}/channel/{channel}/{component}` for the channel component route.

**Comment by kashike** [comment]
https://github.com/korobi/Web/commit/0e3bea53f673be3538284448e2278fe55d071e61
