### ISSUE TITLE
Brush

### ISSUE THREAD

**Issue by Hoolean** [korobi/Korobi#8]
Research more appropriate icons, such as :8ball: or :palm_tree:.

**Comment by lol768** [comment]
Suggest removal and switch to linked timestamps

**Comment by Hoolean** [comment]
Timestamps would seem appropriate as they are usually used to link to individual pieces of content displayed in a list. (see: twitter, [this GitHub comment](https://github.com/korobi/Korobi/issues/8#issuecomment-76562871))

**Comment by bendem** [comment]
That can be done by setting the tabindex of the row container to 0 (making it focusable) and styling :focus. That way, link can be handled easily by just adding #row-id.
Behavior should be consistent across browsers.

[Sample](http://codepen.io/anon/pen/KwBpPM) (click a line, you'll get what I mean, # target is broken because of the codepen iframe)

**Comment by bendem** [comment]
Brushes got nuked

**Comment by lol768** [comment]
excellent
