### ISSUE TITLE
Confusing checkbox behaviour on issues

### ISSUE THREAD

**Issue by lol768** [korobi/Korobi#80]
cc @Zarthus 

```
<@Korobi> [Korobi] ✓ #21: Search — by l​ol768 (https://git.io/vLWER)
<@notZarthus> is that check for done or check for not done
<@lol768> it's a check for not done
```

**Comment by Zarthus** [comment]
we talked about using a checkbox instead previously, respectively coloured orange or green..

```
$repository [ ] #$issueId: $title - by $name ($url)
$repository [x] #$issueId: $title - by $name ($url)
```

**Comment by bendem** [comment]
Github doesn't have a notion of "done/not done". It's `✓` when opened and `✗` when closed. Which makes sense imo.

**Comment by Zarthus** [comment]
except that a check is often used to signify something is done, and a cross often means something isn't.

with the checkbox idea it is easier and less confusing to figure out "well this issue is [not] done"

It makes sense if you get it, but if it's not directly obvious (which it is not), we should alter it.
