### ISSUE TITLE
Have you asked ops for permission to bring the bot? [potential rule breaking]

### ISSUE THREAD

**Issue by Mikaela** [korobi/Korobi#95]
I am op on #znc and no one ever told me that we have any kind of public logging and I have strong suspicion of it being unauthorized by either @DarthGandalf or @psychon who are co-founders of #znc.

From the bottom of [freenode channel guidelines](https://freenode.net/channel_guidelines.shtml):

> If you're considering publishing channel logs, think it through. The freenode network is an interactive environment. Even on public channels, most users don't weigh their comments with the idea that they'll be enshrined in perpetuity. For that reason, few participants publish logs.
> 
> If you're publishing logs on an ongoing basis, your channel topic should reflect that fact. Be sure to provide a way for users to make comments without logging, and get permission from the channel owners before you start. If you're thinking of "anonymizing" your logs (removing information that identifies the specific users), be aware that it's difficult to do it well—replies and general context often provide identifying information which is hard to filter.
> 
> If you just want to publish a single conversation, be careful to get permission from each participant. Provide as much context as you can. Avoid the temptation to publish or distribute logs without permission in order to portray someone in a bad light. The reputation you save will most likely be your own.

**Comment by Mikaela** [comment]
It wasn't authorized by @DarthGandalf and I doubt @psychon did so either, so it has now been kbanned.

**Comment by Mikaela** [comment]
`2015-10-06 09:49:31+0300 <-- Korobi (korobi@is.a.ninja.korobi.io) has quit (K-Lined)`

**Comment by lol768** [comment]
Thank you for the report.

**Comment by kashike** [comment]
Firstly, we'd like to apologise for the inconvenience that we've caused you. We've removed all data relating to freenode from our database and will ensure that the bot doesn't publicly log any channels on the network without explicit permission from the owners of the channel in the future. We will be reviewing all channels on all networks to ensure there are no others the bot is present in without explicit permission.

Our understanding of the guidelines is that they are optional and not all groups adopt them. In the past, we've checked topics to try and ensure the channel has no anti-logging policy before having the bot join, but all of us agree this was not the best approach and we could've done more to ensure the owners of the channel were aware and happy for the logging to take place. We dropped the ball here and we're sorry.

Our goal is to try and make the wealth of information and knowledge distributed in IRC channels more widely available, improve the experience of those managing channels and enable regular channel users to catch up on missed conversations. The logging was not done with any malicious intent and we have, for a long time now, provided a number of privacy-oriented features because we realise logging can cause problems.

Thank you for letting us know about the problem.

**Comment by Mikaela** [comment]
> Our understanding of the guidelines is that they are optional and not all groups adopt them.

This is true, but freenode has never liked public logging bots which don't have permission for what they do and have k-lined them in the past and they will likely continue it in the future.

I am not sure, but I think that this reads in the guidelines instead of policy as channels are free to have public logging if they wish and policy might be seen like enforcing that it's not done.

For getting explicit permission I suggested to Elysia (@Zarthus?) that you might want to consider adopting something like `/msg chanserv set #channel property korobi yes` (metadata that appears in `/msg chanserv info #channel) if the network supports it for seeing if the public logging is allowed. That would require the setter to have +s flag which is usually only given to "super/services ops" and other ops could see that the metadata says that logging is allowed.

**Comment by kashike** [comment]
> This is true, but freenode has never liked public logging bots which don't have permission for what they do and have k-lined them in the past and they will likely continue it in the future. I am not sure, but I think that this reads in the guidelines instead of policy as channels are free to have public logging if they wish and policy might be seen like enforcing that it's not done.

It's unfortunate this isn't more clearly documented. Thank you for letting us know, we'll work with the freenode team to try and get this resolved.

> For getting explicit permission I suggested to Elysia (@Zarthus?) that you might want to consider adopting something like /msg chanserv set #channel property korobi yes (metadata that appears in `/msg chanserv info #channel) if the network supports it for seeing if the public logging is allowed. That would require the setter to have +s flag which is usually only given to "super/services ops" and other ops could see that the metadata says that logging is allowed.

Yes, Zarthus mentioned that suggestion - it sounds like a good idea. Perhaps we can use the TAXONOMY command in order to query this information, in theory it should require less data to be looked up than the INFO command. We'll add this to the TODO list and look at adding an automated system to explain how to set the metadata flag, allow owners to request the bot log their channel, automatically check the metadata and join if everything checks out.

**Comment by Techcable** [comment]
CafeBabe has a thing where ops can /invite a bot.
It is easy for users requires no administrator intervention.
Settings should be able to be modified by channel operators using commands.

**Comment by Mikaela** [comment]
Does it especially need the inviter to be owner or can anyone do that with mode +g (=anyone can invite on Charybdis) or equivalent mode (InspIRCd: +A)?

If anyone can invite the bot, this issue still exists.

**Comment by kashike** [comment]
Korobi was designed to require administrator intervention for joining channels. The way it is designed requires initial settings to be configured when the join "request" is submitted, otherwise Korobi does nothing inside the channel (and limits the amount of chanels Korobi can join further).

We are (slowly) making progress towards making Korobi have better channel owner control, as well as meeting freenode's requirements.

https://github.com/kashike/Felix/commit/0198757a395d83ed5936082e9fcb89bbe2e4a21b
https://github.com/kashike/Internal/issues/34
